# Generated by Django 4.2.5 on 2023-10-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
